### PR TITLE
Replace recipe resource dependencies with normal test dependencies

### PR DESCRIPTION
**Pull request by knutwannheden**
Since neither of the two recipe resource dependencies are used in any of the production code, I don't think there is much point in managing them that way. There is also a downside to it: They end up in the artifact deployed to Maven Central, which both adds to the artifacts size and the risk of them triggering CVE tools (like Nexus), even though they may never get used in the production code.

Fixes: #13

### CODE REVIEW

**Review by JLLeitschuh — APPROVED** [review]
Happy to merge once CI passes. Looks like it's broken because of a missing dependency

**Comment by JLLeitschuh** [comment]
Related: https://github.com/openrewrite/rewrite-build-gradle-plugin/issues/17

**Comment by knutwannheden** [comment]
Hmm. I will take a look.

**Comment by knutwannheden** [comment]
Does the `+` in Gradle versions only work when at the end? Looks that way.

**Comment by JLLeitschuh** [comment]
Thanks for the contribution!

**Pull request merged**
